name: Publish to Cloudflare Pages
on: ['push']
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    environment: "cloudflare pages"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        name: Set up JDK 21
        with:
          java-version: 21
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v4
        name: Set up Gradle
      - run: ./gradlew check :web-app:jsBrowserDistribution
        name: Build project
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        id: cf_publish
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy web-app/build/dist/js/productionExecutable/ --project-name=kcd2dicesim-yawk-at
      - name: Check PR
        uses: 8BitJonny/gh-get-current-pr@3.0.0
        id: pr
      - name: Comment on PR
        if: steps.pr.outputs.pr_found
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: ":rocket: Preview deployed to ${{steps.cf_publish.outputs.deployment-url}}"
          comment-tag: deployment
          pr-number: "${{steps.pr.outputs.number}}"
