name: Build release artifacts
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        name: Set up JDK 21
        with:
          java-version: 21
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v4
        name: Set up Gradle
      - run: ./gradlew :web-app:zip
        name: Build project
      - uses: joutvhu/get-release@v1
        id: get_current_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_current_release.outputs.upload_url }}
          asset_path: web-app/build/libs/web-app.zip
          asset_name: kcd2dicesim.zip
          asset_content_type: application/zip